# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmapper.proto\x1a\x0cstatus.proto\"K\n\nMapRequest\x12\x12\n\nleft_index\x18\x01 \x01(\x05\x12\x13\n\x0bright_index\x18\x02 \x01(\x05\x12\x14\n\x0cNoOfReducers\x18\x03 \x01(\x05\"&\n\x0bMapResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"!\n\x10PartitionRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"1\n\x05\x45ntry\x12\x12\n\ncentroidID\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"G\n\x11PartitionResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x19\n\tpartition\x18\x02 \x03(\x0b\x32\x06.Entry2l\n\rMapperService\x12\"\n\x03Map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12\x37\n\x0cGetPartition\x12\x11.PartitionRequest\x1a\x12.PartitionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=30
  _globals['_MAPREQUEST']._serialized_end=105
  _globals['_MAPRESPONSE']._serialized_start=107
  _globals['_MAPRESPONSE']._serialized_end=145
  _globals['_PARTITIONREQUEST']._serialized_start=147
  _globals['_PARTITIONREQUEST']._serialized_end=180
  _globals['_ENTRY']._serialized_start=182
  _globals['_ENTRY']._serialized_end=231
  _globals['_PARTITIONRESPONSE']._serialized_start=233
  _globals['_PARTITIONRESPONSE']._serialized_end=304
  _globals['_MAPPERSERVICE']._serialized_start=306
  _globals['_MAPPERSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
