# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreducer.proto\x1a\x0cstatus.proto\"1\n\rReduceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cmapper_ports\x18\x02 \x03(\x05\"1\n\rCentroidEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"L\n\x0eReduceResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12!\n\tcentroids\x18\x02 \x03(\x0b\x32\x0e.CentroidEntry2=\n\x0eReducerService\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDUCEREQUEST']._serialized_start=31
  _globals['_REDUCEREQUEST']._serialized_end=80
  _globals['_CENTROIDENTRY']._serialized_start=82
  _globals['_CENTROIDENTRY']._serialized_end=131
  _globals['_REDUCERESPONSE']._serialized_start=133
  _globals['_REDUCERESPONSE']._serialized_end=209
  _globals['_REDUCERSERVICE']._serialized_start=211
  _globals['_REDUCERSERVICE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
